# Site
name: "GELinC"
title: "GELinC"
description: "Grupo de Estudos em Lingu√≠stica Computacional"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: gelincunb@gmail.com

# Authors
authors:
  Juliana:
    name: Juliana
    display_name: Juliana Porto
    avatar: 'assets/images/avatar-juliana.png'
    email: julianaporto169@gmail.com
    web: http://lattes.cnpq.br/6272654670954803
    twitter: https://www.linkedin.com/in/juliana-porto-7070a6198/
    description: "Author of Memoirs, a Bootstrap Medium styled template available for Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
